// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uikvugayerkzqqjyprwc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpa3Z1Z2F5ZXJrenFxanlwcndjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NDc5MzYsImV4cCI6MjA3MDUyMzkzNn0.34Vhetr6y5rFK2KvWq0qNAzHno0cxZJMfwPEFJfBSFY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});